"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var http_1 = require("./http");
Object.defineProperty(exports, "httpSchemaLoader", { enumerable: true, get: function () { return http_1.httpSchemaLoader; } });
var idl_1 = require("./idl");
Object.defineProperty(exports, "idlSchemaLoader", { enumerable: true, get: function () { return idl_1.idlSchemaLoader; } });
var js_1 = require("./js");
Object.defineProperty(exports, "jsSchemaLoader", { enumerable: true, get: function () { return js_1.jsSchemaLoader; } });
var json_1 = require("./json");
Object.defineProperty(exports, "jsonSchemaLoader", { enumerable: true, get: function () { return json_1.jsonSchemaLoader; } });
